version: '3.1'

services:
  mysql_db:
    image: mysql:latest
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: kino_storage-db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./dbdata:/var/lib/mysql/
